name: Verify pull request
on:
  pull_request:
    branches:
      - 'main*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: 'Config npm'
        id: config-npm
        run: |
          echo "@gu-corp:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_NPM_PACKAGES_TOKEN }}" >> .npmrc
          echo "@gusdk:registry=https://test.gusdk.gu.net" >> .npmrc
          echo "test.gusdk.gu.net/:_authToken=${{ secrets.GUSDK_TEST_NPM_TOKEN }}" >> .npmrc
      - name: Install npm modules
        run: npm install
      - name: Run check-types
        run: npm run check-types
      - name: Build
        run: npm run build --if-present
        env:
          # Cookie options.
          # NEXT_PUBLIC_COOKIE_SECURE: true # set to true in HTTPS environment
          # HubSpot
          NEXT_PUBLIC_HUBSPOT_PORTAL_ID: 21059217
          NEXT_PUBLIC_HUBSPOT_CONTACT_FORM_ID_EN: f2176b96-e257-4bf9-a02f-a016a9d4996d
          NEXT_PUBLIC_HUBSPOT_CONTACT_FORM_ID_JA: 8c8bfdfc-1cac-414b-91b0-0837a6585720
          # TermsOfUse docs url
          NEXT_PUBLIC_TERMS_OF_USE_EN: https://docs.google.com/document/d/e/2PACX-1vQMo3aqgnLb174ogmY_Qgjezu3HjzU6IS3oLUZae66oleXqqarqZOxkEhwiTFPzXg-Lews8SLcouDzh/pub?embedded=true
          NEXT_PUBLIC_TERMS_OF_USE_JA: https://docs.google.com/document/d/e/2PACX-1vTOa8TgD_ZUPD3_zEKbdnDwuP4IhtWqQ8zzoPUuGD80Hse_voj3sYOnOdR_W0J0M766vVnF8oMtMAgR/pub?embedded=true
          # Service links
          NEXT_PUBLIC_GET_TOKEN_URL: https://test.account.gu.net/japan-open-chain/get-token
          NEXT_PUBLIC_DEVELOPMENT_PROGRAM_SERVICE_URL: https://test.account.gu.net/development-program
          NEXT_PUBLIC_ENDPOINT_SERVICE_SERVICE_URL: https://test.account.gu.net/endpoint-service
          NEXT_PUBLIC_API_EIP721_SUBGRAPH_SERVER: https://graphnode.sandbox1.japanopenchain.org/subgraphs/name/gulabs/eip721
          NEXT_PUBLIC_IPFS_GATEWAY_URL: https://joc-dashboard.infura-ipfs.io/ipfs/
          # NFT - common
          NEXT_PUBLIC_JOC_URL: https://sandbox1.japanopenchain.org:8545
          NEXT_PUBLIC_TOKEN_ADDRESS: '0x7D34d1f666d6fEaC3C8b560e3DA8Cb4635aEc3a6'
          NEXT_PUBLIC_JOC_CHAIN_ID: 99999
          NEXT_PUBLIC_JOC_TESTNET_CHAIN_ID: 10081
          # Google Tag Manager
          # NEXT_PUBLIC_GTM_ID=xxxxxxxxxxxxxxxxxxxx

      - name: Run lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Backend Test
        run: npm run test:backend
